name: Github pages deployment

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [stable]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist/ta # The folder the action should deploy.
        BUILD_SCRIPT: |
          npm install
          ng build --prod --base-href
          cp dist/ta/index.html dist/ta/404.html
          echo "ta.choy.in" > dist/ta/CNAME

on:
  push:
    branches:
      - master
      - feature/gh-actions
