name: Github pages deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build & Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/ta # The folder the action should deploy.
          CNAME: ta.choy.in
          BUILD_SCRIPT: |
            npm install
            npm run build
            cp dist/ta/index.html dist/ta/404.html
